#!/usr/bin/env bash
# Phase 1C full fold-0 blocker run with partition-parallel shard workers.
#
# Run from code/business_entity_resolution on a CPU machine holding the same
# repository tree (student_resource/dataset/train, artifacts/folds.tsv, configs/,
# artifacts/phase1c/benchmark_eta.json). Test files are not needed or read.
#
#   bash run_phase1c_parallel.sh            # fresh cloud work dir
#   WORK_DIR=../../artifacts/phase1c/work bash run_phase1c_parallel.sh   # reuse local shards
#
# Safe to rerun after interruption: completed shard tasks are skipped.
set -euo pipefail

CONFIG=../../configs/phase1c_fold0.json
WORK_DIR=${WORK_DIR:-../../artifacts/phase1c/work_cloud}
LOGS="$WORK_DIR/logs"
mkdir -p "$LOGS"

python3 -m pip install -q -r requirements.txt
python3 -m pytest -q

# 1. Reproduce the exact 25k Phase 1B pilot on this hardware before anything else.
#    SKIP_PILOT=1 keeps the recorded gate (artifacts/phase1c/pilot_reproduction.json + benchmark_eta.json) instead:
#    the pilot compares against the Phase 1A/1B reference candidates (~260 MB of .npz, regenerated by the Phase 1A/1B
#    commands in the README's development history), which the submission does not ship.
if [ "${SKIP_PILOT:-0}" != "1" ]; then
python3 -m src.evaluate_phase1c --config "$CONFIG" --scope pilot --work-dir "$WORK_DIR" \
  > "$LOGS/cloud_01_pilot.log" 2>&1
fi
python3 - <<'EOF'
import json, sys
result = json.load(open("../../artifacts/phase1c/pilot_reproduction.json"))
if not result["full_run_allowed"]:
    sys.exit("Pilot reproduction is outside the platform tolerance; stop and compare before the full run.\n"
             + json.dumps({k: result[k] for k in ("basis", "platform_tolerance", "nonfloat_routes_identical_to_m1")}, indent=1))
print("pilot reproduction basis:", result["basis"], json.dumps(result["platform_tolerance"]["deltas"]))
EOF

# 2. Disjoint shard workers: target source x route group. Countries stay dynamic.
#    PARALLEL=0 runs one sequential process instead (for machines under ~32 GiB RAM).
if [ "${PARALLEL:-1}" = "0" ]; then
  python3 -m src.evaluate_phase1c --config "$CONFIG" --scope full --work-dir "$WORK_DIR" \
    > "$LOGS/cloud_03_evaluate.log" 2>&1
  tail -n 5 "$LOGS/cloud_03_evaluate.log"
  exit 0
fi
pids=()
for source in 2 3; do
  for group in address_char name_char "name_word exact_name rare_name suffix_exact"; do
    route_args=()
    for route in $group; do route_args+=(--only-route "$route"); done
    name="S${source}_${group%% *}"
    python3 -m src.evaluate_phase1c --config "$CONFIG" --scope full --work-dir "$WORK_DIR" \
      --only-source "$source" "${route_args[@]}" > "$LOGS/cloud_02_worker_${name}.log" 2>&1 &
    pids+=($!)
  done
done
failed=0
for pid in "${pids[@]}"; do wait "$pid" || failed=1; done
if [ "$failed" -ne 0 ]; then
  echo "A shard worker failed; inspect $LOGS and rerun this script to resume." >&2
  exit 1
fi

# 3. Unfiltered pass: verifies every shard hash, evaluates, writes metrics/report/manifest.
python3 -m src.evaluate_phase1c --config "$CONFIG" --scope full --work-dir "$WORK_DIR" \
  > "$LOGS/cloud_03_evaluate.log" 2>&1
tail -n 5 "$LOGS/cloud_03_evaluate.log"
ls -la ../../artifacts/phase1c/fold0_metrics.json ../../artifacts/phase1c/fold0_report.md \
  ../../artifacts/phase1c/run_manifest.json
